Release v1.1.0.0
ElectronicCats/Minino pull request #4
Opened 2024-08-01 19:23 UTC by JahazielLem

### WIFI
- [x] Wardriving
- [x] WiFi sniffer
- [x] WiFi deauther
- [x] DOS Attack (Control with Console and Minino)
- [x] Analizer
- [ ] Wireshark integration
### BLE
- [ ] BLE Sniffer
- [x] BLE Spammer
- [] BLE Spoffing
- [x] BLE Trackers Scanner (AirTags, Tile, etc)
- [ ] Wireshark integration
### Zigbee
- [x] Zigbee sniffer
- [x] Zigbee spoofing (Switch End Device)
- [ ] Wardriving
- [x] Wireshark integration

### Thread
- [x] Thread sniffer
- [x] Thread broadcast
- [ ] Wardriving
- [x] Wireshark integration

### Matter
- [ ] Matter protocol support
- [ ] Matter CLI

### Tools
- [x] OTA Firmware Update
- [x] GPS Location
- [x] GPS Speed
- [x] GPS Time
- [x] SD
- [x] File Manager Web (Local AP and WIFI access)
- [ ] File Manager Local
- [ ] I2C Scanner
- [ ] UART2

### Settings
- [x] Change screensaver
- [x] Change time screensaver

2024-08-01 19:30 UTC, DeimosHall commented
Revisar el número de versión

2024-08-01 19:32 UTC, JahazielLem commented
La version final sera la v1.1.0.0

2024-08-01 19:34 UTC, sabas1080 requested changes
Hacer que pase el github action de pre-commit porfa, revisando testing en dispositivo

2024-08-01 20:57 UTC, sabas1080 commented
Ok para mi, solo cambiar en el display v1.1.0.0

2024-08-01 23:33 UTC, DeimosHall commented
Ya recordé que Roberto me pidió ayuda con ese error en precommit cuando integró ese código que esta dando error, estuvimos en llamada un buen rato y la conclusión a la que llegamos fue desactivarlo para hacer ese commit porque no supimos qué estaba pasando

2024-08-01 23:45 UTC, merged

2024-09-13 13:22 UTC, GordanJorno approved these changes